version: "3.8"

services:
  db:
    container_name: blog_db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    container_name: blog_web
    build: .
    command: python ablog/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"